# Find errors on this file with http://www.yamllint.com/

# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config


# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained

locale                  :   "en-US"  #default["en-US"] format language-TERRITORY , e.g fr, en-GB, es-MX, pt-BR
title                   :   "The Data Journalism Helpline"  #default["repository_name"]
title_separator         :   " | "  #default [" | "]
subtitle                :   "... featuring a range of datajournalism resources." #default [your-repository-tagline]  
description             :   "A curated repository of resources and current information on data journalism or data driven journalism. Includes trends, tools and courseware."  #default [your-repository-tagline]
url                     :   https://dtascribe.github.io/   #See baseurl - On Github Pages you may leave it blank - If you use CNAME use your domain
baseurl                 :     #On Github Pages you may leave it blank. Have a look to: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
words_per_minute        :     #default[200]
timezone                :   "Asia/Calcutta"  #"Europe/Madrid ,see https://jekyllrb.com/docs/configuration/options/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
future                  :   true

# SEO
og_image                :     #default[author.avatar (see below)] or [github-avatar]
twitter_site            : dscribe #Avoid @
author:
  name                  :   Ramachandran  # Name Surname Company
  avatar                :     # Try a square file. Info: Your github avatar on https://github.com/[USERNAME].png
  location              :     # New York, USA 
  links:                
    - url:  https://twitter.com/data_scribe #A link or email: https://twitter.com/jack, mail@example.com
      icon: "fab fa-twitter"
    - url:  https://www.linkedin.com/in/tramachandran/ 
      icon: "fab fa-linkedin" 

fa5_kit_code:  # Your FontAwesome 5 kit code. If not provided a free hosted version (slower) will be loaded:  https://fontawesome.com/ 
fa_v4_support: #Bool Add FontAwesome 4 support 
# Web tracking - Google services https://analytics.google.com/analytics/web/
# gtag_id is the preferred option, see https://developers.google.com/analytics/devguides/collection/gtagjs/migration?hl=en
# analytics provided for backwards compatibility
gtag_id                 :  "G-9EE767GJM9"
analytics_id            :  

# Search providers
# Available free search engines:
# - lunr https://lunrjs.com/ 
# - algolia v4 https://www.algolia.com/ - needs further configuration
# - google custom search engine https://cse.google.es/ 
search:
  provider              : google #Select a provider for enable search: lunr, algolia, google
  label                 :  #default ["Search"] Text on navbar when search is enabled 
  landing_page          :  #default ["/search"] Link on navbar 
  lunr_maxwords         :  #default [30] lunr only - May slow down your site build
  algolia_logo          :  false #Displays algolia logo. Should be set to true if you are on a community plan, otherwise false.  

google_cse_id: #Your cse id
# This site uses jekyll-algolia plugin https://community.algolia.com/jekyll-algolia/
# Recommended additional configuration provided, could be modified. Add your own parameters
algolia:                                                                   
  application_id        : 
  index_name            : 
  search_only_api_key   : 
  files_to_exclude      :        
  extensions_to_index   :   
  searchableAttributes  :   
  customRanking         :          
    
comments:
  provider:         #Enable comments via Disqus https://disqus.com/
  disqus_shortname: #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/

# B. Navigation
# Configure your navbar and the footer of your site

# Navbar: 
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style     : dual #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   : "Home"  # Title in navbar
    url     :  # default["url/baseurl"]
    img     : "docs/assets/img/site/hicon.png"
  nav:
  - title   : Guidance	
    child:		
    - title: Importance of data journalism
      url  : resources/imp
    - title: Entry points
      url  : resources/path
  - title  : Learning - basics		
    child:	
    - title: What is data journalism?
      url  : learning/what
    - title: Learning the basics
      url  : learning/basics
    - title: To code or not
      url  : learning/code
  - title  : About	
    child:
    - title: My (digital) story	
      url  : miscll/story
    - title: Contact	
      url  : miscll/contact


#Social links to be placed on your site footer
footer:
  links:
    - url   : "https://twitter.com/data_scribe"
      icon  : "fab fa-twitter"
    - url   : "https://www.linkedin.com/in/tramachandran/"
      icon  : "fab fa-linkedin"
    - url   : "datajhelp@gmail.com"
      icon  : "fas fa-envelope"

# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts: 
 - url: 'https://fonts.googleapis.com/css2?family=Merriweather&display=swap'
 - url: 'https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap'

# Theme and colors
chulapa-skin: 
  highlight     :  # default["default"]
  skin         : "journal" # Optional predefined skins
  autothemer    :  # Bool: Use autotheming
  vars          :    
    font-family-base: "Merriweather"
    headings-font-family: "Merriweather"
    navbar-chulapa-bg-color: "#EFC94C"
    navbar-chulapa-text-color: "#000000"
    navbar-chulapa-hover-color: "#92140c"
    link-color: "#0A7EC2"
    landingpage-chulapa-bg-color: "#ffffff"
    navbar-chulapa-brand-color: "#92140c"
    footer-chulapa-bg-color: "#fff8f6"
       
# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: "/blog/page:num/"
paginator_maxnum: 3  #default[3] Custom: max of number to be displayed on the paginator


# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
  learning:
    output: true
    permalink: /learning/:name
  resources:
    output: true
    permalink: /resources/:name
  miscll:
    output: true
    permalink: /miscll/:name
collections_dir     : docs/collections
permalink           : /:year:month:day_:title/


# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : "/tags"       #This is where the link on tags would redirect
      cloudcategory_url   : "/categories" #This is where the link on categories would redirect
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_toc          : false
  -
    scope:
      path: ""
      type: "demo"
    values:
      header_type       : "hero"
      show_bottomnavs   : true
      show_sociallinks  : true
      include_on_search : true
      include_on_feed   : true




# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

repository: "dtascribe/ddjhelpline"
